### ISSUE TITLE
目录文字上显示一个红框

### ISSUE THREAD

**Issue by Lilithh** [liangzhenduo0608/TJU-thesis-template#2]
我编译代码后，在目录标题上会有个红色的框框住文字，如下面的截图，不知道怎么去掉。

编译通过xelatex。另外以前目录用hyperref宏包直接\tableofcontents，生成的目录是正常的。

<img width="347" alt="截屏2020-06-20 下午10 27 46" src="https://user-images.githubusercontent.com/32627060/85204303-3797cf80-b346-11ea-954a-332ae44abf7b.png">

**Comment by liangzhenduo** [comment]
红框只是提示的可以点击跳转吧，你看看pdf的打印预览里有吗，我觉得应该是打印不出来的

**Comment by C3ntropy** [comment]
是点击跳转的，按道理这个框不应该显示出来。
但编译生成的pdf里是有的，然后用skim或者pdfexpert看都显示那个框框；之前hyperref宏包生成的目录可以跳转，也没有这个的；
就不知道是哪部份导致产生的

**Comment by liangzhenduo** [comment]
应该是 https://github.com/liangzhenduo0608/TJU-thesis-template/blob/11a7c6c3d8591d41ef04e8fb5159151323f40594/setup/package.tex#L82 引起的，应该可以增加`hidelinks`解决，参考 https://tex.stackexchange.com/questions/823/remove-ugly-borders-around-clickable-cross-references-and-hyperlinks

**Comment by C3ntropy** [comment]
受到启发已解决；发现在这行
https://github.com/liangzhenduo0608/TJU-thesis-template/blob/11a7c6c3d8591d41ef04e8fb5159151323f40594/setup/package.tex#L80
值修改成 (0 0 0) 就去掉边框了

谢谢 :)
